### PR TITLE
Author class

### PR DESCRIPTION
**Pull request by ajay05**
Please review the author class.

### CODE REVIEW

**Comment by JonathanMeans** [comment]
Pretty good. Some nitpicks:

Documentation. It's not immediately clear what `_get_title_and_links` does. The simple fix would be to include something about the return type. Here's the style guide I'm using for this project's docstrings: http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html

It's more Pythonic to use True and False instead of 1 and 0. 

It would be helpful if the fanfic-returning functions could actually return fanfic objects. I'm not 100% about generators, but something like

    return (Fanfic(url) for url in fanfic_urls)

*should* return an iterable that will lazily evaluate each element as needed.

Finally, the functions should only scrape the html the first time they're called. The idea is that they should act more or less just like member variables afterwards. An if-statement to check if they've been assigned a value should do it.

**Comment by ajay05** [comment]
Thank you for your feedback.
I made updates to the author class and its test cases. Let me know, if I missed anything.

I was unable to do the following.
````
It would be helpful if the fanfic-returning functions could actually return fanfic objects. I'm not 100% about generators, but something like

return (Fanfic(url) for url in fanfic_urls)
should return an iterable that will lazily evaluate each element as needed.
````

Where do i implement this in the author class ?

**Comment by JonathanMeans** [comment]
> Where do i implement this in the author class ?

In get_fanfics and get_favorite_fanfics. The thing about JSON streams is the structure is a bit arbitrary. You'd have to read the docs to know that the first element of each fic is the title, for example. Same deal with get_authors. Does that make sense?

Great with everything else, though!

You have any issue with putting this on PyPi, LinkedIn, resumes, etc. when we're done?

**Comment by JonathanMeans** [comment]
(Also, I am far from a testing guru, so I could very well be wrong here. But personally, I find checking every single element of a returned collection a little excessive. If the function does the same thing over and over again, and it gets the first two or three alright, it's probably not going to randomly break in the middle. If it does, that's probably a problem with the inputs, and if you're testing handling of errant input, you should be testing that specifically. So I just like to check the size of the collection, and maybe a couple elements at random. Anything more just makes me hate life.)

**Comment by ajay05** [comment]
I made a few changes to the Author class and added some test cases. Function that were previously returning JSON now return Fanfic object. These are get_fanfics, get_favorite_fanfics and get_favorite_authors.

I modified the test cases to accommodate the changes. Let me know if they look fine.

I have no issues putting this on PyPi, Linkedin, etc.  I intend to do the same if you don't mind  :D

**Comment by JonathanMeans** [comment]
Fantastic! Just going to go ahead and move the fanfiction base url to an import from urls.py. In case... um... the url changes or something. (I just think it's better to have it defined it one place and such. Not a strong opinion.)

**Pull request merged**
